version: '3.4'

services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3001:3001
      - 3001:3001
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
  frontend:
    image: frontend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 3000:3000
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
